version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: DominikHegedus
      POSTGRES_PASSWORD: fneqnfeqcnequbdebqdb134315
      POSTGRES_DB: rps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
